Proje_Dinamik/Proje_Dinamik/Models/Context/Context.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using Proje_Dinamik.Models.Entity;

namespace Proje_Dinamik.Models.Context
{
	public class Context:DbContext
	{

		public DbSet<User> Users { get; set; }
		public DbSet<Customer> Customers { get; set; }
	}
}

Proje_Dinamik/Proje_Dinamik/Models/Entity/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Numerics;
using System.Web;

namespace Proje_Dinamik.Models.Entity
{
	public class Customer
	{
		[Key]
		public int customerID { get; set; }
		public string customerName { get; set; }
		public string customerSurname { get; set; }
		public Int64 customTelephone { get; set; }
		public byte customerAge { get; set; }
		public string customerGender { get; set; }
		public string customerAdress { get; set; }

	}
}

Proje_Dinamik/Proje_Dinamik/Models/Entity/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proje_Dinamik.Models.Entity
{
	public class User
	{
		[Key]
		public int userID { get; set; }
		public string userName { get; set; }
		[DataType(DataType.Password)]
		public string userPass { get; set; }
	}
}

Proje_Dinamik/Proje_Dinamik/Controllers/GuvenlikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Services.Description;
using System.Web.UI.HtmlControls;
using Proje_Dinamik.Models.Entity;
using Proje_Dinamik.Models.Context;

namespace Proje_Dinamik.Controllers
{
	public class GuvenlikController : Controller
	{
		// GET: Guvenlik

		Context db = new Context();
		public ActionResult Login()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Login(User us)
		{
			var values = db.Users.FirstOrDefault(x => x.userName == us.userName && x.userPass == us.userPass);
			if (values != null)
			{
				FormsAuthentication.SetAuthCookie(values.userName, false);
				return RedirectToAction("Index", "Home");
			}
			else
			{
				ModelState.AddModelError("","Hatalı Giriş Yaptınız. Lütfen Bilgilerinizi Kontrol Ediniz !!");
				return View("Login");
			}

		}

	}
}

Proje_Dinamik/Proje_Dinamik/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proje_Dinamik.Models.Context;
using Proje_Dinamik.Models.Entity;
using System.Data.Entity;

namespace Proje_Dinamik.Controllers
{
	public class HomeController : Controller
	{
		Context data = new Context();
		[Authorize]
		public ActionResult Index()
		{
			var values = data.Customers.ToList();
			return View(values);
		}
		[Authorize]
		[HttpGet] // sayfayı olduğu gibi dönderiyoruz.
		public ActionResult CustomerAdd()
		{
			return View();
		}
		[Authorize]
		[HttpPost] // ekleme gerçekleştirilirse dönderiyor.
		public ActionResult CustomerAdd(Customer c)
		{
			data.Customers.Add(c);
			data.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult CustomerDelete(int ID)
		{
			var value = data.Customers.Find(ID);
			data.Customers.Remove(value);
			data.SaveChanges();

			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult CustomerUpdate(int id)
		{
			var value1 = data.Customers.Find(id);
			return View("CustomerUpdate", value1);
		}

		[HttpPost]
		public ActionResult CustomerUpdate(Customer cs)
		{
			var x = data.Customers.Find(cs.customerID);

			x.customerName = cs.customerName;
			x.customerSurname = cs.customerSurname;
			x.customerAge = cs.customerAge;
			x.customerGender = cs.customerGender;
			x.customTelephone = cs.customTelephone;
			x.customerAdress = cs.customerAdress;
			data.SaveChanges();

			return RedirectToAction("Index");
		}


		public ActionResult CustomerDetails(int id)
		{
			var value2 = data.Customers.Find(id);
			return View("CustomerDetails", value2);

		}

		[Authorize]
		public ActionResult Details()
		{
			var values = data.Customers.SqlQuery("customerDetails").ToList();
			return View(values);
		}

	}
}

Proje_Dinamik/Proje_Dinamik/Views/Guvenlik/Login.cshtml
@model Proje_Dinamik.Models.Entity.User

@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login User</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="~/Loginpage/images/icons/favicon.ico" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Loginpage/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/Loginpage/css/main.css">
	<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				@using (Html.BeginForm("Login", "Guvenlik", FormMethod.Post))
				{
					<span class="login100-form-title p-b-32">
						Kullanıcı Giriş Ekranı
					</span>

					<span class="txt1 p-b-11">
						Kullanıcı Adı
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate="Username is required">
						<input class="input100" type="text" name="userName" placeholder="Kullanıcı Adı giriniz." required="">
						<span class="focus-input100"></span>
					</div>

					<span class="txt1 p-b-11">
						Şifre
					</span>
					<div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100" type="password" name="userPass" placeholder="Parola giriniz." required="">
						<span class="focus-input100"></span>
					</div>
					<br />

					<div class="container-login100-form-btn" style="justify-content: center">
						<button class="login100-form-btn" >
							Giriş Yap
						</button>
					</div>
				}
				<br />

				<div class="alert alert-light" role="alert">
					@Html.ValidationSummary(true)
				</div>
			</div>
		</div>
	</div>


</body>
</html>

Proje_Dinamik/Proje_Dinamik/Views/Home/CustomerAdd.cshtml
@model Proje_Dinamik.Models.Entity.Customer
@{
	ViewBag.Title = "CustomerAdd";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Müşteri Ekleme Ekranı</h2>
<br />

<form method="post" class="form-group">
	<div>
		<label>Müşteri Ad</label>
		@Html.TextBoxFor(x => x.customerName, new { @class = "form-control", @placeholder = "Adınız.", @required = "" })
	</div>
	<div>
		<label>Müşteri Soyad</label>
		@Html.TextBoxFor(x => x.customerSurname, new { @class = "form-control", @placeholder = "Soyadınız.", @required = "" })
	</div>
	<div>
		<label>Yaş</label>
		@Html.TextBoxFor(x => x.customerAge, new { @class = "form-control", @placeholder = "Yaşınız.", @required = "" })
	</div>
	<div>
		<label>Cinsiyet</label>
		@Html.TextBoxFor(x => x.customerGender, new { @class = "form-control", @placeholder = "Cinsiyetiniz.", @required = "" })
	</div>
	<div>
		<label>Telefon</label>
		@Html.TextBoxFor(x => x.customTelephone, new { @class = "form-control", @placeholder = "Telefon no.", @required = "" })
	</div>
	<div>
		<label>Adres</label>
		@Html.TextBoxFor(x => x.customerAdress, new { @class = "form-control", @placeholder = "Adresiniz.", @required = "" })
	</div>

	<br />
	<div>
		<a href="/Home/Index/"><button class="btn btn-primary">Kaydet</button></a>
	</div>

</form>

Proje_Dinamik/Proje_Dinamik/Views/Home/CustomerDetails.cshtml
@model Proje_Dinamik.Models.Entity.Customer
@{
    ViewBag.Title = "CustomerDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detaylı Müşteri Bilgi Ekranı</h2>

<form method="post" class="form-group">

	<div>
		<label>Müşteri Ad</label>
		@Html.TextBoxFor(x => x.customerName, new { @class = "form-control", @readonly=true })
	</div> <br />
	<div>
		<label>Müşteri Soyad</label>
		@Html.TextBoxFor(x => x.customerSurname, new { @class = "form-control", @readonly = true })
	</div><br />
	<div>
		<label>Yaş</label>
		@Html.TextBoxFor(x => x.customerAge, new { @class = "form-control", @readonly = true })
	</div><br />
	<div>
		<label>Cinsiyet</label>
		@Html.TextBoxFor(x => x.customerGender, new { @class = "form-control", @readonly = true })
	</div><br />
	<div>
		<label>Telefon</label>
		@Html.TextBoxFor(x => x.customTelephone, new { @class = "form-control", @readonly = true })
	</div> <br />
	<div>
		<label>Adres</label>
		@Html.TextBoxFor(x => x.customerAdress, new { @class = "form-control", @readonly = true })
	</div>
	<br />

	<div class="invisible">
		@Html.TextBoxFor(x => x.customerID, new { @class = "form-control" })
	</div>

</form>

Proje_Dinamik/Proje_Dinamik/Views/Home/CustomerUpdate.cshtml
@model Proje_Dinamik.Models.Entity.Customer

@{
	ViewBag.Title = "CustomerUpdate";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Müşteri Güncelleme Ekranı</h2>
<br />

<form method="post" class="form-group">

	<div>
		<label>Müşteri Ad</label>
		@Html.TextBoxFor(x => x.customerName, new { @class = "form-control", @required="" })
	</div><br />
	<div>
		<label>Müşteri Soyad</label>
		@Html.TextBoxFor(x => x.customerSurname, new { @class = "form-control", @required = "" })
	</div><br />
	<div>
		<label>Yaş</label>
		@Html.TextBoxFor(x => x.customerAge, new { @class = "form-control", @required = "" })
	</div><br />
	<div>
		<label>Cinsiyet</label>
		@Html.TextBoxFor(x => x.customerGender, new { @class = "form-control", @required = "" })
	</div><br />
	<div>
		<label>Telefon</label>
		@Html.TextBoxFor(x => x.customTelephone, new { @class = "form-control", @required = "" })
	</div><br />
	<div>
		<label>Adres</label>
		@Html.TextBoxFor(x => x.customerAdress, new { @class = "form-control", @required = "" })
	</div>
	<br />
	<div>
		<button class="btn btn-warning">Güncelle</button>
	</div>
	<div class="invisible">
		@Html.TextBoxFor(x => x.customerID, new { @class = "form-control" })
	</div>

</form>

Proje_Dinamik/Proje_Dinamik/Views/Home/Details.cshtml
@using Proje_Dinamik.Models.Entity
@model List<Customer>
@{
	ViewBag.Title = "Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Müşterilerin Detaylı Bilgi Ekranı</h2>
<br />

<div>
	<table class="table table-bordered ">
		<thead>
			<tr>
				<th scope="col">Müşteri Sıra No</th>
				<th scope="col">Müsteri ID</th>
				<th scope="col">Müşteri Ad</th>
				<th scope="col">Müşteri Soyad</th>
				<th scope="col">Yaş</th>
				<th scope="col">Cinsiyet</th>
				<th scope="col">Telefon No</th>
				<th scope="col">Adres</th>
			</tr>
		</thead>
		<tbody>

			@{ int sirano = 0;}

			@foreach (var x in Model)
			{
				sirano++;
				<tr>
					<th>@sirano</th>
					<th>@x.customerID</th>
					<td>@x.customerName</td>
					<td>@x.customerSurname</td>
					<td>@x.customerAge</td>
					<td>@x.customerGender</td>
					<td>@x.customTelephone</td>
					<td>@x.customerAdress</td>
				</tr>
			}

		</tbody>

	</table>
</div>

Proje_Dinamik/Proje_Dinamik/Views/Home/Index.cshtml
@using Proje_Dinamik.Models.Entity
@model List<Customer>

@{
	ViewBag.Title = "BasicCrm";
}

<h2>Müşteri Listesi</h2>
<br />

<div>
	<table class="table table-bordered ">
		<thead>
			<tr>
				<th scope="col">Müşteri Sıra No</th>
				<th scope="col">Müşteri Ad</th>
				<th scope="col">Müşteri Soyad</th>
				<th scope="col">GÜNCELLE</th>
				<th scope="col">DETAY</th>
				<th scope="col">SİL</th>
			</tr>
		</thead>
		<tbody>
		@{ int sirano = 0;}
		@foreach (var x in Model)
		{
			sirano++;
			<tr>
				<th>@sirano</th>
				<td>@x.customerName</td>
				<td>@x.customerSurname</td>

				<td><a href="/Home/CustomerUpdate/@x.customerID" class="btn btn-success">GÜNCELLE</a></td>
				<td><a href="/Home/CustomerDetails/@x.customerID" class="btn btn-info">DETAY</a></td>
				<td><a href="/Home/CustomerDelete/@x.customerID" class="btn btn-danger">SİL</a></td>
			</tr>
		}

		</tbody>

	</table>
</div>

Proje_Dinamik/Proje_Dinamik/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BasicCrm", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
					<li>@Html.ActionLink("Müsteriler", "Index", "Home")</li>
	                <li>@Html.ActionLink("Müsteri Ekleme", "CustomerAdd", "Home")</li>
	                <li>@Html.ActionLink("Müsteri Detay", "Details", "Home")</li>
	                
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>